version: '3.7'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/12/main/
    environment:
      - POSTGRES_USER=doit
      - POSTGRES_PASSWORD=doit
      - POSTGRES_DB=doit_dev

volumes:
  postgres_data:
