version: '3.7'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    volumes:
      - ./services/web/:/home/app/web/
    # command: gunicorn doit_app:doit --bind 0.0.0.0:8080 --worker-class aiohttp.GunicornWebWorker
    command: gunicorn --reload --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
     # - 8080
    env_file:
      - ./.env.prod
    depends_on:
      - db
  cron:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    volumes:
      - ./services/web/:/home/app/web/
    command: python run_crontab.py
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  nginx:
    build: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
