* dev
** sprint 0
*** TODO send all templates in template directory to each configured channel
*** TODO add upper body exercises
    https://topfitnesstutorials.com/top-10-upper-body-exercices-no-equipment/

** sprint 1
*** TODO setup docker for prod
*** TODO distinguish between dev and prod mode
    so that it sends message to the test channels and cron is every minute etc
*** TODO save user responses to posts
    show breakdown of exercises per week

*** TODO allow users to configure their own templates with bot commands
    do validation checks on the crontabs being sent through
    - can't be more than X times an hour
      - depending on context like links etc
    we can get pretty wild here?  is this turning into a PA? (personal assistant and a public address system)
*** TODO commands
    Show all/selected exercise images
*** TODO flask migrate
    https://blog.miguelgrinberg.com/post/how-to-add-flask-migrate-to-an-existing-project

** sprint 2
*** TODO patreon
**** people can request/suggest built-in templates
**** add extra ways for users to build templates

** backlog
   telegram/whatsapp/teams

* journey
** naming
*** app
    Doit
    RemindMeBoutIt (RMBI/rmbi)

*** bots
    BepePete
    ReMindbot
    ReminderBot
    RemindMeBot

** setting up for production
   https://testdriven.io/blog/dockerizing-flask-with-postgres-gunicorn-and-nginx/

** templates
   #+begin_src yml
   #+end_src

   {}
* resources
** exercises
*** current list
    "upper": [
        Exercise(
            "Push Ups",
            "20 reps",
            "https://media.giphy.com/media/Kjj5yTgDdiuvC/giphy.gif",
	    EXTREME VERSION: INDEX FINGERS ONLY
        ),
        Exercise(
            "Burpees",
            "10 reps",
            "https://media.giphy.com/media/23hPPMRgPxbNBlPQe3/giphy.gif",
	    
        ),
        Exercise(
            "Shoulder Press Ups",
            "20 reps",
            "https://www.youtube.com/watch?v=KcvLM-Q4eFo",
	    EXTREME VERSION: HAND STAND PRESS UP?
        ),
        Exercise(
            "Inch Worms",
            "10 reps",
            "https://media.giphy.com/media/UTXzXAwUHGx8MDEtPS/giphy.gif",
	    EXTREME VERSION: 
        ),
        Exercise(
            "Decline Push-up", "10 reps", "https://www.youtube.com/watch?v=aq2xZxfrQlM"
	    EXTREME VERSION: HAND STAND PUSH UP?
        ),
        Exercise(
            "Tricep Dips",
            "20 reps",
            "https://media.giphy.com/media/13HOBYXe87LjvW/giphy.gif",
	    EXTREME VERSION: NO FEET TOUCHING THE GROUND
        ),
        Exercise(
            "Close-Grip Push Ups",
            "10 reps",
            "http://www.shapefit.com/pics/chest-exercises-push-ups-close-hand-position.gif",
	    EXTREME VERSION: ONE HAND
        ),
        Exercise(
            "Kick Throughs",
            "20 reps",
            "https://raw.githubusercontent.com/alecvn/slack-gymbot/master/kick_through.gif",
	    EXTREME VERSION: 
        ),
    ],
    "legs": [
        Exercise(
            "Squats",
            "20 reps",
            "https://media.giphy.com/media/1qfKN8Dt0CRdCRxz9q/giphy.gif",
	    EXTREME VERSION: DEADLIFT THE HEAVIEST THING IN YOUR HOUSE/APARTMENT
        ),
        Exercise(
            "Lunges",
            "20 reps",
            "https://media.giphy.com/media/l3q2Q3sUEkEyDvfPO/giphy.gif",
	    
        ),
        Exercise(
            "High Knees",
            "30 seconds",
            "https://media.giphy.com/media/l0HlNOsSRC0Bts7iU/giphy.gif",
	    
        ),
        Exercise(
            "Mountain Climbers",
            "30 seconds",
            "https://media.giphy.com/media/bWYc47O3jSef6/giphy.gif",
	    
        ),
        Exercise(
            "Squat Jumps",
            "20 reps",
            "https://media.giphy.com/media/nmuUOAEvrKTLDT3yTn/giphy.gif",
	    
        ),
        Exercise(
            "Side Lunges",
            "20 reps",
            "https://media.giphy.com/media/Pj0wnhvHp3AHMM5ILf/giphy.gif",
	    
        ),
        Exercise(
            "Reverse Lunges",
            "20 reps",
            "https://media.giphy.com/media/3o6ozoyJ0IlfuEsuXu/giphy.gif",
	    
        ),
    ],
    "core": [
        Exercise(
            "Sit Ups",
            "20 reps",
            "https://media.giphy.com/media/9EFCRjJF4EqB2/giphy.gif",
	    
        ),
        Exercise(
            "Planks",
            "1 min",
            "https://media.giphy.com/media/xT8qBff8cRRFf7k2u4/giphy.gif",
        ),
        Exercise(
            "Side Planks",
            "30 seconds",
            "https://media.giphy.com/media/3o6gDUTsbepOYTqTRK/giphy.gif",
        ),
        Exercise(
            "Butterfly Situps",
            "10 reps",
            "https://i.makeagif.com/media/8-23-2016/W_ZqTQ.gif",
        ),
        Exercise(
            "Leg Raises",
            "20 reps",
            "https://media.giphy.com/media/2LtUR24UvCZdC/giphy.gif",
        ),
        Exercise(
            "Bicycle Crunches",
            "20 reps",
            "https://media.giphy.com/media/TMNCtgJGJnV8k/giphy.gif",
        ),
    ],
*** core
    https://www.youtube.com/watch?v=3p8EBPVZ2Iw
